function F = Deformed_Sphere()
    F = @(X,Y,Z) ...
    X.^2 + Y.^2 + Z.^2 ...
    - (3 .* ( ...
        1 ...
        + 0.2 .* sin(5 .* acos(Z ./ sqrt(X.^2 + Y.^2 + Z.^2))) ...
        .* cos(3 .* atan2(Y,X)) ...
    )).^2;
end